name: mimo_spark
description: MIMO_SPARK (Flutter / OBD2)
publish_to: 'none'

version: 1.2.3+23

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wakelock_plus: ^1.2.8
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  google_fonts: ^6.2.13
  flutter_tts: ^3.8.3
  syncfusion_flutter_gauges: ^24.1.41
  sensors_plus: ^6.1.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/IMG_0730.JPG"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/data/
    - assets/images/
    - assets/images/spark2.png
