name: mimo_spark
description: MIMO_SPARK (Flutter / OBD2)
publish_to: 'none'

version: 1.2.8+28

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wakelock_plus: ^1.2.8
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  google_fonts: ^6.2.13
  syncfusion_flutter_gauges: ^24.1.41
  sensors_plus: ^6.1.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  flutter_background_service: ^5.0.7
  speech_to_text: 6.1.1
  sqflite: ^2.3.3
  path: ^1.9.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/spark2.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: assets/images/spark2.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    color: "#000000"
    image: assets/images/spark2.png

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/data/
    - assets/images/
    - assets/images/spark alpha.jpeg
    - assets/images/spark_alpha_transparent.png
    - assets/images/Adobe Express - file.png
    - assets/images/spark_marker.png
