name: Mimo-Spark-Android-Build-APK
# Run for Android only
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Create Native Folders on Cloud
        run: flutter create --org com.mimo . --platforms=android --no-overwrite

      - name: Upgrade Kotlin Version
        run: |
          # Flutter 3.22 ne met plus 'ext.kotlin_version' par défaut, mais certains packages l'exigent.
          # 1. On l'ajoute de force tout en haut du build.gradle
          sed -i '1i buildscript { ext.kotlin_version = "1.9.22" }' android/build.gradle
          # 2. On met à jour la déclaration si elle existe dans settings.gradle
          sed -i 's/id "org.jetbrains.kotlin.android" version ".*" apply false/id "org.jetbrains.kotlin.android" version "1.9.22" apply false/' android/settings.gradle || true

      - name: Add Android Network Permissions & Cleartext
        run: |
          # 1. Update Package Name in Manifest (Generated by flutter create)
          sed -i 's/package=".*"/package="com.mimo.spark"/' android/app/src/main/AndroidManifest.xml
          
          # 2. Inject ALL mandatory permissions for Spark (Internet + WiFi + Location)
          # We place them before the <application tag
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET" />\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />\n    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />\n    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />\n    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />\n    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />' android/app/src/main/AndroidManifest.xml
          
          # 3. Inject Cleartext Traffic permission and update App Label
          sed -i 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          sed -i 's/android:label=".*"/android:label="Mimo Spark"/' android/app/src/main/AndroidManifest.xml
          
          # Verification
          cat android/app/src/main/AndroidManifest.xml
                    
      - name: Flutter Pub Get
        run: flutter pub get

      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons

      - name: Build APK (Android)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mimo-Spark-Android-Build-APK
          path: build/app/outputs/flutter-apk/app-release.apk
