name: Mimo-Spark-Android-Build-APK
# Run for Android only
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Create Native Folders on Cloud
        run: flutter create --org com.mimo . --platforms=android --no-overwrite

      - name: Inject Native Shield
        run: |
          mkdir -p android/app/src/main/kotlin/com/mimo/spark
          cp native/android/MainActivity.kt android/app/src/main/kotlin/com/mimo/spark/MainActivity.kt

      - name: Upgrade Kotlin Version
        run: |
          # Flutter 3.22 ne met plus 'ext.kotlin_version' par défaut, mais certains packages l'exigent.
          # 1. On l'ajoute de force tout en haut du build.gradle
          sed -i '1i buildscript { ext.kotlin_version = "1.9.22" }' android/build.gradle
          # 2. On met à jour la déclaration si elle existe dans settings.gradle
          sed -i 's/id "org.jetbrains.kotlin.android" version ".*" apply false/id "org.jetbrains.kotlin.android" version "1.9.22" apply false/' android/settings.gradle || true

      - name: Add Android Network Permissions & Cleartext (Clean Replacement)
        run: |
          # 1. Update Package Name in build.gradle (generated by flutter create)
          # sed -i 's/applicationId ".*"/applicationId "com.mimo.spark"/' android/app/build.gradle
          
          # 2. Remplacement du Manifest par notre version propre testée
          cp native/android/AndroidManifest.xml android/app/src/main/AndroidManifest.xml
          
          # Verification
          cat android/app/src/main/AndroidManifest.xml
                    
      - name: Flutter Pub Get
        run: flutter pub get

      - name: Generate Native Splash (Android + iOS)
        run: dart run flutter_native_splash:create

      - name: Prepare iOS Icon Placeholders
        run: |
          mkdir -p ios/Runner/Assets.xcassets/AppIcon.appiconset
          # flutter_launcher_icons needs the folder to exist
          ls ios/Runner/Assets.xcassets/AppIcon.appiconset/ || true

      - name: Generate App Icons (Android + iOS)
        run: flutter pub run flutter_launcher_icons

      - name: Build APK (Android)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mimo-Spark-Android-Build-APK
          path: build/app/outputs/flutter-apk/app-release.apk
