name: MVS7000-Web-Build
on:
  push:
    branches: [ "mvs7000_simulator" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Create Web Platform
        run: flutter create --platforms=web . --no-overwrite

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href "/"

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MVS7000-Web-Build
          path: build/web
